version: '3'

services:
  # The GitLab container itself
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.mydomain.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.domain.com'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['backup_upload_remote_directory'] = 's3-backup-bucket'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.domain.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab@domain.com"
        gitlab_rails['smtp_password'] = "EMAILPASSWORD"
        gitlab_rails['smtp_domain'] = "domain.com"
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - traefik-proxy
      - default
    ports:
      - "2222:22"
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab_insecure.entrypoints=web
      - traefik.http.routers.gitlab_insecure.rule=Host(`gitlab.domain.com`)
      - traefik.http.routers.gitlab_insecure.middlewares=redirect@file

      - traefik.http.routers.gitlab.entrypoints=web-secure
      - traefik.http.routers.gitlab.rule=Host(`gitlab.domain.com`)
      - traefik.http.routers.gitlab.tls.certresolver=letsencrypt
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.docker.network=traefik-proxy

      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`gitlab.domain.com`)
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc
      - traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=2222

networks:
  traefik-proxy:
    external: true

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
